# Generated by Django 3.1.7 on 2021-03-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210301_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lanmu',
            old_name='beloong',
            new_name='belong',
        ),
    ]
