# Generated by Django 3.1.7 on 2021-03-02 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210301_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinglun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_art', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinglun_article', to='blog.article')),
                ('belong_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinglun_user', to='blog.userinfo')),
            ],
        ),
    ]
