# Generated by Django 3.1.7 on 2021-03-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_pinglun'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinglun',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
